<?php

namespace BBLDN\OpenRTP\Enum;

enum LossReasonCodeEnum: int
{
    case BID_WON = 0;

    case INTERNAL_ERROR = 1;

    case IMPRESSION_OPPORTUNITY_EXPIRED = 2;

    case INVALID_BID_RESPONSE = 3;

    case INVALID_DEAL_ID = 4;

    case INVALID_AUCTION_ID = 5;

    case INVALID_ADVERTISER_DOMAIN = 6;

    case MISSING_MARKUP = 7;

    case MISSING_CREATIVE_ID = 8;

    case MISSING_BID_PRICE = 9;

    case MISSING_MINIMUM_CREATIVE_APPROVAL_DATA = 10;

    case BID_WAS_BELOW_AUCTION_FLOOR = 100;

    case BID_WAS_BELOW_DEAL_FLOOR = 101;

    case LOST_TO_HIGHER_BID = 102;

    case LOST_TO_A_BID_FOR_A_DEAL = 103;

    case BUYER_SEAT_BLOCKED = 104;

    case CREATIVE_FILTERED_GENERAL = 200;

    case CREATIVE_FILTERED_PENDING_PROCESSING_BY_EXCHANGE = 201;

    case CREATIVE_FILTERED_DISAPPROVED_BY_EXCHANGE = 202;

    case CREATIVE_FILTERED_SIZE_NOT_ALLOWED = 203;

    case CREATIVE_FILTERED_INCORRECT_CREATIVE_FORMAT = 204;

    case CREATIVE_FILTERED_ADVERTISER_EXCLUSIONS = 205;

    case CREATIVE_FILTERED_APP_STORE_ID_EXCLUSIONS = 206;

    case CREATIVE_FILTERED_NOT_SECURE = 207;

    case CREATIVE_FILTERED_LANGUAGE_EXCLUSIONS = 208;

    case CREATIVE_FILTERED_CATEGORY_EXCLUSIONS = 209;

    case CREATIVE_FILTERED_CREATIVE_ATTRIBUTE_EXCLUSIONS = 210;

    case CREATIVE_FILTERED_AD_TYPE_EXCLUSIONS = 211;

    case CREATIVE_FILTERED_ANIMATION_TOO_LONG = 212;

    case CREATIVE_FILTERED_NOT_ALLOWED_IN_DEAL = 213;

    case CREATIVE_FILTERED_INVALID_SKADNETWORK = 214;

    case CREATIVE_FILTERED_APP_BUNDLE_EXCLUSIONS = 215;
}
